CC=gcc

all: task1 task2 task3 task4

task1: task1.c
	$(CC) $(CFLAGS) $< -o $@

task2: task2.c
	$(CC) $(CFLAGS) $< -o $@

task3: task3.c
	$(CC) $(CFLAGS) $< -o $@

task4: task4.c
	$(CC) $(CFLAGS) $< -o $@

clean:
	rm -f task1 task2 task3 task4
